vim.keymap.set("v", "<", "<gv", { noremap = true, silent = true })
vim.keymap.set("v", ">", ">gv", { noremap = true, silent = true })
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<leader>w", "<cmd>w<CR>", { noremap = true, silent = true, desc = "Write current buffer" })
vim.keymap.set("n", "<leader>q", "<cmd>wqa<CR>", { noremap = true, silent = true, desc = "Quit Neovim" })
vim.keymap.set("n", "<leader>h", "<cmd>noh<CR>", { noremap = true, silent = true, desc = "Remove search highlights" })
